### ISSUE TITLE
Any geojson format ?

### ISSUE THREAD

**Issue by ghost** [lotfio/algeria-administrative-divisions#1]
thanks a lot.

**Comment by lotfio** [comment]
You are welcome, no geo location information for now. I will be adding it in the future

**Comment by ghost** [comment]
I found a very neat one, but not administrative divisions, for the country.
This one [dza_admbnda_unhcr2020_shp](https://data.humdata.org/dataset/3d17274d-0812-4b21-b87a-4854af4eb244/resource/34f317e5-7de9-4e1b-a457-91ab786dc952)
that I converted to geojson. tell me if you need it in this repo.

**Comment by lotfio** [comment]
Yes ! that would be awesome.

**Comment by ghost** [comment]
here it is:
https://file.io/1Y7nmZrLU6MK 

Check in https://geojson.io (can hang the browser as it is a bit heavy)

-- converted using http://gipong.github.io/shp2geojson.js/

**Comment by ghost** [comment]
It is the best I found so far !!! with islands included and a very exact delimitation
